import addressRoutes from "./address.routes.js";
import auditLogRoutes from "./auditLog.routes.js";
import authRoutes from "./auth.routes.js";
import bankRoutes from "./bank.routes.js";
import commissionRoutes from "./commission.routes.js";
import kycRoutes from "./kyc.routes.js";
import loginLogRoutes from "./loginLog.routes.js";
import permissionRoutes from "./permission.routes.js";
import roleRoutes from "./role.routes.js";
import serviceRoutes from "./service.routes.js";
import systemSettingRoutes from "./systemSetting.routes.js";
import userRoutes from "./user.routes.js";
import walletRoutes from "./wallet.routes.js";
import fundRequestRoutes from "./fundRequest/fundRequest.routes.js";
import employeeRoutes from "./employee.routes.js";
import aadhaarRoutes from "./aadhaar/aadhaar.routes.js";
import panRoutes from "./pan/pan.routes.js";
import payoutRoutes from "./payout/payout.route.js";
import transactionRoutes from "./transaction.routes.js";
import bankVerificationRoutes from "./bankVerification/bankVerification.routes.js";
import webhookRoutes from "./webhook.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import ledgerRoutes from "./ledger.routes.js";

export function StaticRoutes(app) {
  app.use("/api/v1/addresses", addressRoutes);
  app.use("/api/v1/audit-logs", auditLogRoutes);
  app.use("/api/v1/auth", authRoutes);
  app.use("/api/v1/banks", bankRoutes);
  app.use("/api/v1/commissions", commissionRoutes);
  app.use("/api/v1/kycs", kycRoutes);
  app.use("/api/v1/login-logs", loginLogRoutes);
  app.use("/api/v1/permissions", permissionRoutes);
  app.use("/api/v1/roles", roleRoutes);
  app.use("/api/v1/services", serviceRoutes);
  app.use("/api/v1/system-setting", systemSettingRoutes);
  app.use("/api/v1/users", userRoutes);
  app.use("/api/v1/employees", employeeRoutes);
  app.use("/api/v1/aadhaar", aadhaarRoutes);
  app.use("/api/v1/pan", panRoutes);
  app.use("/api/v1/wallet", walletRoutes);
  app.use("/api/v1/fund-req", fundRequestRoutes);
  app.use("/api/v1/txn", transactionRoutes);
  app.use("/api/v1/payout", payoutRoutes);
  app.use("/api/v1/bank-verification", bankVerificationRoutes);
  app.use("/api/v1/webhook", webhookRoutes);
  app.use("/api/v1/dashboard", dashboardRoutes);
  app.use("/api/v1/ledger", ledgerRoutes);
}
