// Predefined business roles (jo system mein fixed hain)
export const BUSINESS_ROLES = [
  "AZZUNIQUE",
  "RESELLER",
  "WHITELABEL",
  "STATE HEAD",
  "MASTER DISTRIBUTOR",
  "DISTRIBUTOR",
  "RETAILER",
];

export const ROLE_HIERARCHY = {
  AZZUNIQUE: ["RESELLER"],
  RESELLER: ["WHITELABEL"],
  WHITELABEL: ["STATE_HEAD", "MASTER_DISTRIBUTOR", "DISTRIBUTOR", "RETAILER"],
  STATE_HEAD: ["MASTER_DISTRIBUTOR", "DISTRIBUTOR", "RETAILER"],
  MASTER_DISTRIBUTOR: ["DISTRIBUTOR", "RETAILER"],
  DISTRIBUTOR: ["RETAILER"],
};
