// Predefined business roles (jo system mein fixed hain)
export const BUSINESS_ROLES = [
  "AZZUNIQUE",
  "RESELLER",
  "WHITE LABEL",
  "STATE HEAD",
  "MASTER DISTRIBUTOR",
  "DISTRIBUTOR",
  "RETAILER",
];

export const ROLE_HIERARCHY = {
  AZZUNIQUE: ["RESELLER"],
  RESELLER: ["WHITE LABEL"],
  "WHITE LABEL": [
    "STATE HEAD",
    "MASTER DISTRIBUTOR",
    "DISTRIBUTOR",
    "RETAILER",
  ],
  "STATE HEAD": ["MASTER DISTRIBUTOR", "DISTRIBUTOR", "RETAILER"],
  "MASTER DISTRIBUTOR": ["DISTRIBUTOR", "RETAILER"],
  DISTRIBUTOR: ["RETAILER"],
};
